[project]
name = "pyqttest"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyside6>=6.9.2",
]

[dependency-groups]
dev = [
    "pytest>=8.4.1",
    "pytest-qt>=4.5.0",
]
